---
title: "Stim analyses"
author: "Helio"
date: "06/04/2021"
output: html_document
---


Multilevel Polynomial Modelling

Aggregated face action plot

```{r}
require(tidyverse)
require(ggplot2)

```

Figure 2A
```{r}

# figure preferences
#p<- list()
# sf = 1 # scaling factor
p$graphstyle1 <-  theme(#base plot theme
  
  # axis lines
  axis.line.y = element_line(color="black"),
  axis.line.x = element_line(color="black"),
  
  axis.title.y=element_text(size = 14*(sf+.5), margin=margin(0,5,0,0)),
  axis.title.x=element_text(size = 14*(sf+.5), margin=margin(0,5,0,0)),
  
  # text
  strip.text.x = element_text(size = 11*(sf+.5),  colour = "black"),
  strip.text.y = element_text(size = 11*(sf+.5),  colour = "black"),
  
  text=element_text(size = 14, family = "sans"),
  axis.text.x = element_text(size = 14, family = "sans", colour = "black",),
  axis.text.y = element_text(size = 14, family = "sans", colour = "black"),
  
  
  # panel
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  panel.background = element_blank(),
  # panel.background = element_rect(fill="transparent"),
  # panel.border = element_rect(fill="transparent"),
  # strip shades (reco rectagles)
   strip.background = element_blank(),
  
  # legend
  legend.position = "top",
  legend.key = element_rect(colour = "transparent", fill="transparent"),
  #legend.direction = "horizontal",
  #legend.key.size = unit(.5, "cm"),
  #legend.text = element_text(size = 10*sf+.3),
  legend.title = element_text(size = 10*(sf+.3))
  #legend.key.size = unit(.5, "cm"),
  #legend.text = element_text(size = 10*sf),
  #legend.title=element_blank(),
  #legend.text = element_blank(),
  #axis.ticks = element_blank(),
)



```


Figure 2 in the paper is called Figure 4 in the code bellow
```{r}

# prepare the data
colnames(db_of7_new)

# new facet labels for dataset
dataset_labs<- c("High prot.", "Low prot.")
names(dataset_labs)<- c("ADFES", "JEFFE")

colnames(db_of7_new)
View(figure4)

figure4<- db_of7_new %>%
  group_by(Emotion,Dataset, morph,video, )%>%
  arrange( Emotion,Dataset, morph,video,timebin)%>%
  mutate(face_action_AVG2 = face_action_AVG- mean(face_action_AVG[1:4], na.rm = TRUE))%>%
  ggplot(aes(timebin, face_action_AVG2,color = Emotion))+
  stat_smooth(aes(group = video), geom = 'line', se = F, alpha = .3)+
  stat_smooth(aes(group = Emotion), geom = 'line', se = F, size = 1.5, alpha = .7,
              linetype = "dashed")+
  facet_grid(Dataset~morph)+
    xlab("Time (s)")+
  ylab("Face action (pix)")+
  p$graphstyle1+
  scale_color_brewer(palette = "Dark2")+
   geom_hline(yintercept = 0, size = 1, alpha = .5,linetype = "dotted")

figure4<- figure4+
  facet_grid(Dataset~morph,
             labeller = labeller(morph = db_of7_new$morph, Dataset = dataset_labs))+
  theme(legend.position = "none")
  

figure4

# export clean data for figure 2(4)

data_fig2<- db_of7_new %>%
  group_by(Emotion,Dataset, morph,video )%>%
  arrange( Emotion,Dataset, morph,video,timebin)%>%
  mutate(face_action_AVG2 = face_action_AVG- mean(face_action_AVG[1:4], na.rm = TRUE))%>%
  select(c(Emotion,Dataset, morph,video,timebin,face_action_AVG2))


saveRDS(data_fig2, "data_fig2.rds") # we write in rds due to potential data loss in other encoding formats
write_csv(data_fig2, "data_fig2.csv")

```


Figure 3
```{r}
# rename emotions consistently joy = happiness
db_of7_new$Em<- if_else(db_of7_new$Em == "Jo", "Ha", db_of7_new$Em)
db_of7_new$Em<- substr(db_of7_new$Emotion, 1,2)

db_of7_new$Emotion<- if_else(db_of7_new$Emotion == "Joy", "Happiness", as.character(db_of7_new$Emotion))

Figure3 <- db_of7_new %>%
  group_by(Emotion,Em,Dataset, morph,video)%>%
  arrange(Emotion, Em, Dataset, morph,video,timebin)%>%
  mutate(face_action_AVG2 = face_action_AVG- mean(face_action_AVG[1:4], na.rm = TRUE))%>%
  summarise_if(is.numeric, mean, na.rm = TRUE)%>%
  ggplot(aes(Em, face_action_AVG2, colour = Emotion))+
  
  geom_boxplot()+
  geom_jitter(alpha = .5)+
  facet_grid(Dataset~morph,
             labeller = labeller(morph = db_of7_new$morph, Dataset = dataset_labs))+

  xlab("Emotion")+
  ylab("Average face action (pix)")+
  # theme_classic()+
  p$graphstyle1+
  scale_color_brewer(palette = "Dark2")+
  theme(axis.text.x = element_text(size = 16),
        axis.text.y = element_text(size = 16),
        axis.title.y = element_text(size = 20),
        axis.title.x = element_text(size = 20),
        legend.position = "top")+
   geom_hline(yintercept = 0, size = 1.5, alpha = .5,linetype = "dotted")
  
  # scale_color_brewer(palette = "Dark2")
  

Figure3

library(patchwork)

  
Figure3Panel<-  (Figure3/figure4) +plot_annotation(tag_levels = "A")

ggsave("Figure3Panel.png", Figure3Panel, device = "png", width = 12, height = 12,
       dpi = 900)

ggsave("Figure3Panel.tiff", Figure3Panel, device = "tiff", width =12, height = 12,
       dpi = 900)

ggsave("Figure3.png", Figure3, device = "png", width = 10, height = 8,
       dpi = 900)
ggsave("Figure3.tiff", Figure3, device = "tiff", width = 10, height = 8,
       dpi = 900)

ggsave("Figure4.png", figure4, device = "png", width = 10, height = 8,
       dpi = 900)
ggsave("Figure4.tiff", figure4, device = "tiff", width = 10, height = 8,
       dpi = 900)


# db_of7_new_2021 %>%
#   group_by(Emotion,Dataset, morph,video)%>%
#   # arrange(Emotion, Em, Dataset, morph,video,timebin)%>%
#   # mutate(face_action_AVG2 = face_action_AVG- mean(face_action_AVG[1:4], na.rm = TRUE))%>%
#   summarise_if(is.numeric, mean, na.rm = TRUE)%>%
#   ggplot(aes(Emotion, speed_face_action_AVG2, colour = Emotion))+
#   
#   
#   geom_boxplot()+
#   geom_jitter()+
#   stat_summary(geom = 'pointrange')+
#   facet_grid(Dataset~morph,
#              labeller = labeller(morph = db_of7_new$morph, Dataset = dataset_labs))+
#   xlab("Emotion")+
#   ylab("Average face action speed (pix/s)")+
#   # theme_classic()+
#   p$graphstyle1+
#   scale_color_brewer(palette = "Dark2")+
#   theme(axis.text.x = element_text(size = 16),
#         axis.text.y = element_text(size = 16),
#         axis.title.y = element_text(size = 20),
#         axis.title.x = element_text(size = 20),
#         legend.position = "top")+
#    geom_hline(yintercept = 0, size = 1, alpha = .5,linetype = "dotted")


# save data for figure 3
data_fig3<- db_of7_new %>%
  group_by(Emotion,Em,Dataset, morph,video)%>%
  arrange(Emotion, Em, Dataset, morph,video,timebin)%>%
  mutate(face_action_AVG2 = face_action_AVG- mean(face_action_AVG[1:4], na.rm = TRUE))%>%
  summarise_if(is.numeric, mean, na.rm = TRUE)%>%
  select(c(Emotion,Dataset, morph,video,face_action_AVG2))


saveRDS(data_fig3, "data_fig3.rds") # we write in rds due to potential data loss in other encoding formats
write_csv(data_fig3, "data_fig3.csv")

```



Formal modeling



Polynomial analyses
```{r}

# Prepare data

db_of7_new_2021<- db_of7_new %>%
  group_by(Emotion,Dataset, morph,video, )%>%
  arrange( Emotion,Dataset, morph,video,timebin)%>%
  mutate(face_action_AVG2 = face_action_AVG- mean(face_action_AVG[1:4], na.rm = TRUE))%>%
  mutate(speed_face_action_AVG2 = abs(face_action_AVG2- lead(face_action_AVG2))/abs(timebin - lead(timebin)))

db_of7_new %>%
  group_by(Emotion,Dataset, morph,video, )%>%
  arrange( Emotion,Dataset, morph,video,timebin)%>%
  mutate(face_action_AVG2 = face_action_AVG- mean(face_action_AVG[1:4], na.rm = TRUE))%>%
  mutate(speed_face_action_AVG2 = abs(face_action_AVG2- lead(face_action_AVG2))/abs(timebin - lead(timebin)))%>%
  subset(morph == "Morph")%>%
  ggplot(aes(timebin, speed_face_action_AVG2, color = Emotion))+
  geom_line(aes(group = video), se = F)+
  facet_grid(Dataset~morph)

# create polynomials
time <- unique(db_of7_new$timebin)
time_poly <- poly(time, 4) # defult raw = FALSE = orogonal
time_poly

db_of7_new$stim_id

db_of7_new <- db_of7_new %>%
  group_by(Emotion,Dataset, morph,video, )%>%
  arrange( Emotion,Dataset, morph,video,timebin)%>%
  mutate(face_action_AVG2 = face_action_AVG- mean(face_action_AVG[1:4], na.rm = TRUE))%>%
  mutate(ot1  = poly(time, 1)[,1])%>%
  mutate(ot2  = poly(time, 2)[,2])%>%
  mutate(ot3  = poly(time, 3)[,3])%>%
  mutate(ot4  = poly(time, 4)[,4])

db_of7_new$video_id<- paste(db_of7_new$face_unique, paste0(db_of7_new$Emotion))
# stim 
db_of7_new


```

fit lmer
```{r}
# set contrasts
options(contrasts = c("contr.sum","contr.poly"))

library(lmerTest)

polymodels<- list()
# polymodels$poly_orig_full1 <- lmer(face_action_AVG ~ (ot1+ot2+ot3+ot4) * 
#                                      Emotion*Dataset*morph+
#                                     
#                                     (1 + ot1+ot2+ot3 |stim_id),
#                                      # (0 + Dataset| face_unique),
#                        REML = FALSE,
#                        verbose = TRUE,
#                        data = db_of7_new)
# 
# 
# 
# relgrad <- with(polymodels$poly_orig_full1@optinfo$derivs,solve(Hessian,gradient))
# max(abs(relgrad)) #0.000110469


polymodels$poly_orig_full1 <- lmer(face_action_AVG2 ~ 
                                     (ot1+ot2+ot3) * 
                                     Emotion*Dataset*morph+
                                    
                                    (1 + ot1+ot2 |stim_id)+
                                     (0+ot3| stim_id),
                                     # (0 + morph| stim_id),
                       REML = FALSE,
                       verbose = TRUE,
                       data = db_of7_new)

plot(polymodels$poly_orig_full1)

summary(polymodels$poly_orig_full1)

anova(polymodels$poly_orig_full1)

sjPlot::tab_model(polymodels$poly_orig_full1)

relgrad <- with(polymodels$poly_orig_full1@optinfo$derivs,solve(Hessian,gradient))
max(abs(relgrad)) #0.000110469



db_of7_new$Dataset_contr <- if_else(db_of7_new$Dataset =="ADFES", .5, -.5)

polymodels$poly_orig_full2 <- lmer(face_action_AVG2 ~ (ot1+ot2+ot3) * Emotion*
                                     Dataset_contr*VideoType_contrast +
                                    
                                    (1 + ot1+ot2+ot3 |video_id), 
                                     (0 +ot3 |stim_id)
                                     ,
                       REML = FALSE,
                       verbose = TRUE,
                       data = db_of7_new)


anova(polymodels$poly_orig_full2)
summary(polymodels$poly_orig_full2)

MuMIn::r.squaredGLMM(polymodels$poly_orig_full2)

emmeans::emmeans(polymodels$poly_orig_full2 , pairwise ~ 
                   Emotion|Dataset_contr)

relgrad <- with(polymodels$poly_orig_full2@optinfo$derivs,solve(Hessian,gradient))
max(abs(relgrad))
# polymodels$poly_orig_full3 <- lmer(face_action_AVG2 ~ (ot1+ot2+ot3) * Emotion*
#                                      Dataset_contr*VideoType_contrast +
#                                     
#                                     (1 + ot1+ot2 |video_id)+ 
#                                      (0 +ot3 |video_id),
#                        REML = FALSE,
#                        verbose = TRUE,
#                        data = db_of7_new)


# dataset for polynomial analyses


data_poly_analyses<- db_of7_new %>%select(c('face_action_AVG2', 'Emotion', 'video_id','timebin',
                                          'VideoType_contrast',
                                          # 'Videotype',
                                          'Dataset_contr', 'Dataset',
                                          'ot1', 'ot2', 'ot3', 'ot4'))

saveRDS(data_poly_analyses, "data_poly_analyses.rds")
write_csv(data_poly_analyses, "data_poly_analyses.csv")



```